apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "openIM.cron_task" . }}-{{ include "openIM.fullname" . }}
  labels:
    {{- include "openIM.labels" . | nindent 4 }}
    app: {{include "openIM.cron_task" . }}
spec:
  replicas: {{ .Values.cron_task.replicaCount }}
  selector:
    matchLabels:
      {{- include "openIM.selectorLabels" . | nindent 6 }}
      app: {{include "openIM.cron_task" . }}
  template:
    metadata:
      annotations:
        {{- with .Values.cron_task.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "openIM.selectorLabels" . | nindent 8 }}
        app: {{include "openIM.cron_task" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openIM.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.cron_task.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: [ "./open_im_cron_task" ]
          securityContext:
            {{- toYaml .Values.cron_task.securityContext | nindent 12 }}
          image: "{{ .Values.cron_task.repository }}:{{ .Values.cron_task.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cron_task.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /Open-IM-Server/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: notification
              mountPath: /Open-IM-Server/config/notification.yaml
              subPath: notification.yaml
              readOnly: true
          env:
            - name: CONFIG_NAME
              value: "/Open-IM-Server"
            - name: USUAL_CONFIG_NAME
              value: "/Open-IM-Server"
          resources:
            {{- toYaml .Values.cron_task.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "openIM.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
        - name: notification
          configMap:
            name: {{ include "openIM.fullname" . }}
            items:
              - key: notification.yaml
                path: notification.yaml
      {{- with .Values.cron_task.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cron_task.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cron_task.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
