apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: kubegems
  name: kubegems

---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  kind: helm
  url: https://charts.kubegems.io/kubegems
  values:
    global:
      kubegemsVersion: v1.22.2
      imageRegistry: docker.io
      storageClass: local-hostpath # change me to use a different storage class
    dashboard:
      service:
        type: NodePort
    ingress:
      hostname: dashboard.kubegems.io # change me to use a production hostname