apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "atoms.fullname" . }}
  labels:
    {{- include "atoms.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "atoms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "atoms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "atoms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: AIGES_WRAPPER_VERSION
            value: v1
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /root/go/src/git.xfyun.cn/AIaaS/atmos/atmos
            -  -m=1
            -  -p={{.Values.cfg.project}}
            -  -g={{.Values.cfg.cluster}}
            -  -s={{.Values.cfg.service}}
            -  -u=http://{{.Release.Name}}-polaris-companion:6868
            -  -c=atmos.cfg
          ports:
            - name: tcp 
              containerPort: 9988 
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tcp 
          readinessProbe:
            tcpSocket:
              port: tcp
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
