apiVersion: v2
appVersion: 6.1.1
dependencies:
- condition: deepflow-agent.enabled
  name: deepflow-agent
  repository: ""
  version: '*.*.*'
- name: clickhouse
  repository: ""
  version: '*.*.*'
- name: mysql
  repository: ""
  version: '*.*.*'
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.32.*
description: An automated observability platform for cloud-native developers.
home: https://github.com/deepflowys/deepflow
keywords:
- deepflow
kubeVersion: '>=1.16.0-0'
name: deepflow
sources:
- https://github.com/deepflowys/deepflow
type: application
version: 0.1.002
