apiVersion: v2
appVersion: 1.11.0
description: A Helm chart for installing Percona XtraDB Cluster Databases using the PXC Operator.
home: https://www.percona.com/doc/kubernetes-operator-for-pxc/kubernetes.html
icon: https://artifacthub.io/image/0b8875cd-6661-4269-9cf6-0fd92d59017b@1x
maintainers:
- email: ivan.pylypenko@percona.com
  name: cap1984
- email: tomislav.plavcic@percona.com
  name: tplavcic
- email: sergey.pronin@percona.com
  name: spron-in
- email: natalia.marukovich@percona.com
  name: nmarukovich
name: pxc-db
version: 1.11.5
