kind: Job
apiVersion: batch/v1
metadata:
  name: kafka-topic-creator
  namespace: kafka
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: kafka-topic-creator
          image: docker.io/bitnami/kafka:3.4.1-debian-11-r0
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: bitnami-kafka-0.bitnami-kafka-headless.kafka.svc.cluster.local:9092
          command:
            - /bin/bash
            - -c
            - |
              topics=("msg_to_mongo" "ws2ms_chat" "ms2ps_chat" "msg_to_modify")
              for topic in "${topics[@]}"
              do
                  echo "create topic $topic"
                  /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server $KAFKA_BOOTSTRAP_SERVER --replication-factor 1 --partitions 12 --topic $topic
              done
      restartPolicy: Never
  backoffLimit: 4
