apiVersion: v1
data:
  application.yml: |
    #tomcat配置
    server:
      port: 8099
      tomcat:
        max-threads: 3000
        max-connections: 3000
    #  ssl:
    #    key-store: classpath:keystore.p12
    #    key-store-password: iflytek
    #    keyStoreType: PKCS12
    #    keyAlias: tomcat

    #http请求的端口号
    httpport: 8096

    spring:
      datasource:
        url: jdbc:mysql://{{.Release.Name}}-mysql:3306/{{.Values.cynosure.mysql.database}}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
        username: {{.Values.cynosure.mysql.username}}
        #password: gqpxotzfHNoBKOS6Fug2aWsJJS3d3AV2PocN4hxuwpsO5sWNjOHbK7BTdJiBbVMa/LPZqmLnB2UEL5R57aSsHw==
        password: {{.Values.cynosure.mysql.password}}
        driver-class-name: com.mysql.jdbc.Driver
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
          #filter:
        #config:
        #enabled: true
        initialSize: 10
        minIdle: 10
        maxActive: 30
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10
        # 合并多个DruidDataSource的监控数据
        #useGlobalDataSourceStat: true

      #出现错误时, 直接抛出异常
      mvc:
        throw-exception-if-no-handler-found: true
        #关闭默认的favicon.ico
        favicon:
          enabled: false

      #不要为工程中的资源文件建立映射
      resources:
        add-mappings: false
        chain:
          enabled: true
          cache: false
          html-application-cache: false
          strategy:
            content:
              enabled: false
            fixed:
              enabled: false
      #session设置
      session:
        store-type: none
        cookie:
          name: polaris_cynosure

            #redis配置
            #redis:
            # Redis数据库索引（默认为0）
            #database: 0
            #      cluster:
            #        nodes: 172.16.154.235:6479,172.16.154.235:6480,172.16.154.235:6481
            # Redis服务器地址
            # host: 10.1.86.212
            # Redis服务器连接端口
            # port: 6379
            #      # Redis服务器连接密码（默认为空）
            # password:
            # 连接超时时间（毫秒）
            #timeout: 0
            # pool:
            # 连接池最大连接数（使用负值表示没有限制）
            #max-active: 100
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            #max-wait: -1
            # 连接池中的最大空闲连接
            #max-idle: 8
          # 连接池中的最小空闲连接
          #min-idle: 0

      http:
        #文件大小设置
        multipart:
          max-file-size: 1MB
          max-request-size: 10MB
          enabled: true
        #配置response编码
        encoding:
          force: true

      #缓存类型
      cache:
        type: guava


    #mybatis配置
    mybatis:
      config-locations: classpath:mybatis/mybatis-config.xml
      mapper-locations: classpath:mybatis/mapper/*.xml
      type-aliases-package: com.iflytek.ccr.polaris.cynosure.domain

    #pagehelper分页插件
    pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql

    #日志配置
    logging:
      config: classpath:config/logback-spring.xml
      level:
        com.iflytek.ccr.polaris.cynosure.mapper: DEBUG

    #健康检查管理
    management:
      health:
        redis:
          enabled: false

    #配置路径
    configPath: /polaris/config/
    #服务发现路径
    servicePath: /polaris/service/
    #会话共享
    sessionShare: 0
    #druid监控配置
    ip: 172.16.59.2,127.0.0.1

    #检查session最大间隔时间，此值决定两次操作之间最大的时间间隔
    maxInterval: 160000
    #对外开发接口认证配置
    private_key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALE10TMPaMvwM+ub8G84B+X2gWyh5aS2d9DGDUj2vNAE7u3CsTtTDncWtW63XLws+RlxkQenjzKs+36LJCXOKp31DO6RXBS30LguigISwb9Q5H2sjS9H62Q6lRjtfmK9g0ntr8+UbVOY2QB1WJ9UPzhl6IleCwTddKqPojUeaJe/AgMBAAECgYEAgAGL+AIthQMhvhOKfgxPSEHkA4B+zZgwvFITzpzMjsbBgGWeeGfqjwOMU0mIZzVlSofKZ2kV+1kQ4bvIhLaD+RU0xWr0FSLLcCB5VdStqrnoMFyMaUP9mXQSXk1kvrXzcMABsCvhgWyCDeR7terxHhAPLrEwYAjWoO9xBF75kiECQQD+WNkVMcAftmEHz/01m1NihpNAZJ23Mi47iuTf6HV2f0dLXSfmQZk21PdoPbGsyiTdk/YZCh7Uu6UbyGDk0E0dAkEAslyjYl+Vuv19p40wByjkBwKZmyLkPGQsMEAz1opgH0SxenzKbrf/F8gmAET8t2eHru897yf1BIMQibWDEQFNiwJAY1tPydC6bWjwNH4SOtunUiih4xiq54Jpvwa9653CLP0BW7ZTPMZJVLsSvpzDCG2awxfmnddvPcjjcZvwBdI9HQJAPvn+pmlhkNiYWWS8pIqHmQIOAnzbYYdtIsxIgWPydJfoonsVbuqAo4EECexR3uArRFUs5RiSprkwSa9RS9vN6QJBAM1sAbI23Uig/rcFkMcXbyvk5nFhGUDyW5NRO973ryIgZv5KGZZeT211EjBwpA0x1X74Ag0OVSSIZizAiy5Aars=
    valid_interval: 300000
    #配置文件分页数
    #config_page_size: 100
kind: ConfigMap
metadata:
  name: {{ include "polaris.fullname" . }}-cynosure
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
