apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-init-config-job"
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: init-config 
        image: "public.ecr.aws/iflytek-open/athena-job:v1.0.0"
        args: ["--password","123456", "--configAddr", "{{.Release.Name}}-polaris-cynosure:8099"]
