apiVersion: v2
appVersion: 3.0.0
dependencies:
- condition: installCRDs
  name: eck-operator-crds
  repository: ""
  version: 3.0.0
description: Elastic Cloud on Kubernetes (ECK) operator
home: https://github.com/elastic/cloud-on-k8s
icon: https://helm.elastic.co/icons/eck.png
keywords:
- Logstash
- Elasticsearch
- Kibana
- APM Server
- Beats
- Enterprise Search
- Elastic Stack
- Operator
kubeVersion: '>=1.21.0-0'
maintainers:
- email: eck@elastic.co
  name: Elastic
name: eck-operator
type: application
version: 3.0.0
