apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "openIM.rpc_third" . }}-{{ include "openIM.fullname" . }}
  labels:
    {{- include "openIM.labels" . | nindent 4 }}
    app: {{include "openIM.rpc_third" . }}
spec:
  replicas: {{ .Values.third.replicaCount }}
  selector:
    matchLabels:
      {{- include "openIM.selectorLabels" . | nindent 6 }}
      app: {{include "openIM.rpc_third" . }}
  template:
    metadata:
      {{- with .Values.third.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openIM.selectorLabels" . | nindent 8 }}
        app: {{include "openIM.rpc_third" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openIM.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.third.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.third.securityContext | nindent 12 }}
          image: "{{ .Values.third.repository }}:{{ .Values.third.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.third.pullPolicy }}
          command: [ "./open_im_third" ]
          args: [ "--port", "10200", "--prometheus_port","20200" ]
          ports:
            - name: rpc
              containerPort: 10200
              protocol: TCP
            - name: metrics
              containerPort: 20200
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: rpc
          readinessProbe:
            tcpSocket:
              port: rpc
          volumeMounts:
            - name: config
              mountPath: /Open-IM-Server/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: notification
              mountPath: /Open-IM-Server/config/notification.yaml
              subPath: notification.yaml
              readOnly: true
          env:
            - name: CONFIG_NAME
              value: "/Open-IM-Server"
            - name: USUAL_CONFIG_NAME
              value: "/Open-IM-Server"
          resources:
            {{- toYaml .Values.third.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "openIM.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
        - name: notification
          configMap:
            name: {{ include "openIM.fullname" . }}
            items:
              - key: notification.yaml
                path: notification.yaml
      {{- with .Values.third.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.third.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.third.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
