apiVersion: v1
kind: Service
metadata:
  name: {{include "openIM.rpc_user" . }}-{{ include "openIM.fullname" . }}
  labels:
    {{- include "openIM.labels" . | nindent 4 }}
    app: {{include "openIM.rpc_user" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "openIM.selectorLabels" . | nindent 4 }}
    app: {{include "openIM.rpc_user" . }}
