apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-cert-manager-check"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-cert-manager-check"
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: cert-manager-check
          image: busybox:latest
          command: ["sh", "-c", "until echo exit | telnet cert-manager-webhook.cert-manager.svc 443; do echo waiting for cert-manager; sleep 10; done;"]
