apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "zot.fullname" . }}
spec:
  dnsNames:
    - {{ include "zot.fullname" . }}.{{.Release.Namespace}}.svc
    - {{ include "zot.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local
    {{- range .Values.extraDNSNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    kind: Issuer
    name: zot-selfsigned-issuer
  secretName: {{.Values.tlsSecretName}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: zot-selfsigned-issuer
spec:
  selfSigned: {}
