apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "openIM.rpc_conversation" . }}-{{ include "openIM.fullname" . }}
  labels:
    {{- include "openIM.labels" . | nindent 4 }}
    app: {{include "openIM.rpc_conversation" . }}
spec:
  replicas: {{ .Values.conversation.replicaCount }}
  selector:
    matchLabels:
      {{- include "openIM.selectorLabels" . | nindent 6 }}
      app: {{include "openIM.rpc_conversation" . }}
  template:
    metadata:
      {{- with .Values.conversation.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openIM.selectorLabels" . | nindent 8 }}
        app: {{include "openIM.rpc_conversation" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openIM.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.conversation.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.conversation.securityContext | nindent 12 }}
          image: "{{ .Values.conversation.repository }}:{{ .Values.conversation.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.conversation.pullPolicy }}
          command: [ "./open_im_conversation" ]
          args: [ "--port", "10230", "--prometheus_port","20230" ]
          ports:
            - name: rpc
              containerPort: 10230
              protocol: TCP
            - name: metrics
              containerPort: 20230
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: rpc
          readinessProbe:
            tcpSocket:
              port: rpc
          volumeMounts:
            - name: config
              mountPath: /Open-IM-Server/config/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: notification
              mountPath: /Open-IM-Server/config/notification.yaml
              subPath: notification.yaml
              readOnly: true
          env:
            - name: CONFIG_NAME
              value: "/Open-IM-Server"
            - name: USUAL_CONFIG_NAME
              value: "/Open-IM-Server"
          resources:
            {{- toYaml .Values.conversation.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "openIM.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
        - name: notification
          configMap:
            name: {{ include "openIM.fullname" . }}
            items:
              - key: notification.yaml
                path: notification.yaml
      {{- with .Values.conversation.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.conversation.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.conversation.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
